local capture = require("capture")
local gameConfig = require("gameConfig")
local composer = require( "composer" )
local Sprite = require("Sprite")
--composer.gotoScene( "leaderBoardScene" , {params = {stype = "local"}})
display.setStatusBar( display.HiddenStatusBar )
composer.gotoScene( "scenes.game")
--composer.gotoScene( "newHighScoreScene")
capture:startCapture()
Sprite.addSheet(gameConfig.SHEET_PIXEL_EFFECT, "sprites/pixeleffect.png", "sprites.pixeleffect")
print( "Screen Ratio: "..display.pixelWidth .."/" ..display.actualContentWidth..":".. display.contentWidth..":")