local capture = require("capture")
display.setStatusBar( display.HiddenStatusBar )
local composer = require( "composer" )
--composer.gotoScene( "leaderBoardScene" , {params = {stype = "local"}})
composer.gotoScene( "scenes.game")
--composer.gotoScene( "newHighScoreScene")
capture:startCapture()
print( "Screen Ratio: "..display.pixelWidth .."/" ..display.actualContentWidth..":".. display.contentWidth..":")